import type { ChosenMedia } from "~/lib/types/user-posts/media";

export type DirectMessageSession = {
  id?: string; // This should be auto-generated by firebase
  initiatorId: string;
  receiverIds: string[];
  messages: DirectMessage[];
  createdAt?: number;
  updatedAt?: number;
};

export type DirectMessage = {
  id?: string; // We need to generate this via our code
  message: DirectMessageData;
  createdAt: number;
  seenBy?: Array<{
    userId: string;
    createdAt: number;
  }>;
};

export type DirectMessageData = {
  text: string;
  sender: string;
  imageUrl?: string | null;
  multimedia?: ChosenMedia[] | null;
};
